### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by moskomule** [sungyubkim/GBML#1]
Hi @sungyubkim, thank you for publishing this great repository.

I found that your MAML algorithm on ResNet increases the GPU memory usage every iteration and causes a CUDA out of memory error.
I ran it by `python main.py --alg MAML --net ResNet`. I use PyTorch 1.3.1 with CUDA 10.1 and the latest dependencies.

Thank you.

**Comment by sungyubkim** [comment]
Thanks for helpful issue.
I used ResNet only for CAVIA.
So I checked your setting and found that ResNet on MAML yields some OOM problems.
Therefore, I recommend using 1st order approximation of MAML which can be implemented as
`params = fmodel.parameters(time=-1)`
`outer_grad = torch.autograd.grad(outer_loss, params)`

instead of original MAML 'if is_train' condition

I found that this requires about 7gb of GPU memory which is reasonable.

**Comment by moskomule** [comment]
Thank you for a quick response. I will check.
Is it higher's problem?

**Comment by sungyubkim** [comment]
Maybe it is.
I am not sure about the exact cause of the problem.

**Comment by sungyubkim** [comment]
I found that the main cause of this issue is related to python garbage collection.
Now you can fix this problem by augmenting 

import gc 

and

gc.collect() 

after model.outer_loop call

this will save your GPU memory significantly.
